export const browserCoreExamples = [
  "resonix browser status",
  "resonix browser start",
  "resonix browser stop",
  "resonix browser tabs",
  "resonix browser open https://example.com",
  "resonix browser focus abcd1234",
  "resonix browser close abcd1234",
  "resonix browser screenshot",
  "resonix browser screenshot --full-page",
  "resonix browser screenshot --ref 12",
  "resonix browser snapshot",
  "resonix browser snapshot --format aria --limit 200",
  "resonix browser snapshot --efficient",
  "resonix browser snapshot --labels",
];

export const browserActionExamples = [
  "resonix browser navigate https://example.com",
  "resonix browser resize 1280 720",
  "resonix browser click 12 --double",
  'resonix browser type 23 "hello" --submit',
  "resonix browser press Enter",
  "resonix browser hover 44",
  "resonix browser drag 10 11",
  "resonix browser select 9 OptionA OptionB",
  "resonix browser upload /tmp/resonix/uploads/file.pdf",
  'resonix browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "resonix browser dialog --accept",
  'resonix browser wait --text "Done"',
  "resonix browser evaluate --fn '(el) => el.textContent' --ref 7",
  "resonix browser console --level error",
  "resonix browser pdf",
];
