#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${RESONIX_INSTALL_E2E_IMAGE:-${RESONIXDBOT_INSTALL_E2E_IMAGE:-resonix-install-e2e:local}}"
INSTALL_URL="${RESONIX_INSTALL_URL:-${RESONIXDBOT_INSTALL_URL:-https://resonix.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
RESONIX_E2E_MODELS="${RESONIX_E2E_MODELS:-${RESONIXDBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e RESONIX_INSTALL_URL="$INSTALL_URL" \
  -e RESONIX_INSTALL_TAG="${RESONIX_INSTALL_TAG:-${RESONIXDBOT_INSTALL_TAG:-latest}}" \
  -e RESONIX_E2E_MODELS="$RESONIX_E2E_MODELS" \
  -e RESONIX_INSTALL_E2E_PREVIOUS="${RESONIX_INSTALL_E2E_PREVIOUS:-${RESONIXDBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e RESONIX_INSTALL_E2E_SKIP_PREVIOUS="${RESONIX_INSTALL_E2E_SKIP_PREVIOUS:-${RESONIXDBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
